pipeline {
    environment {
       PATH = "$WORKSPACE/miniconda/bin:$PATH"
    }
    agent {
        label 'tsa'
    }

    post {
        always{
            echo 'Cleaning up workspace'
            deleteDir()
        }
    }
    stages {
        stage('setup miniconda') {
            steps {
                sh '''#!/usr/bin/env bash
                set -e
                bash setup_miniconda.sh -p ${WORKSPACE}
                '''
            }
        }
        stage('build package') {
            steps {
                sh '''#!/usr/bin/env bash
                set -e
                cd ${WORKSPACE}/icon-timeseries
                source ${WORKSPACE}/miniconda/etc/profile.d/conda.sh
                conda init bash
                conda activate
                ./setup_env.sh -n icon-timeseries -u
                conda activate icon-timeseries
                pip install --no-deps .
                '''
            }
        }
        stage('test') {
            steps {
                sh '''#!/usr/bin/env bash
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda init bash
                conda activate icon-timeseries
                cd ${WORKSPACE}/icon-timeseries
                pytest tests
                '''
            }
        }
        stage('dev-environment') {
            steps {
                sh '''#!/usr/bin/env bash
                set -e
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda init bash
                conda activate
                cd ${WORKSPACE}/icon-timeseries
                ./setup_env.sh -n icon-timeseries -d -u
                conda activate dev-icon-timeseries
                pip install --no-deps --editable .
                '''
            }
        }
        stage('dev-test') {
            steps {
                sh '''#!/usr/bin/env bash
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda init bash
                conda activate dev-icon-timeseries
                cd ${WORKSPACE}/icon-timeseries
                pytest tests
                '''
            }
        }
        stage('pinned-environment') {
            steps {
                sh '''#!/usr/bin/env bash
                set -e
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda init bash
                conda activate
                cd ${WORKSPACE}/icon-timeseries
                ./setup_env.sh -n pinned-icon-timeseries
                conda activate pinned-icon-timeseries
                pip install --no-deps .
                '''
            }
        }
        stage('pinned-test') {
            steps {
                sh '''#!/usr/bin/env bash
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda activate pinned-icon-timeseries
                cd ${WORKSPACE}/icon-timeseries
                pytest tests
                '''
            }
        }
        stage('pinned-dev-environment') {
            steps {
                sh '''#!/usr/bin/env bash
                set -e
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda init bash
                conda activate
                cd ${WORKSPACE}/icon-timeseries
                ./setup_env.sh -n pinned-icon-timeseries -d
                conda activate pinned-dev-icon-timeseries
                pip install --no-deps --editable .
                '''
            }
        }
        stage('pinned-dev-test') {
            steps {
                sh '''#!/usr/bin/env bash
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda activate pinned-dev-icon-timeseries
                cd ${WORKSPACE}/icon-timeseries
                pytest tests
                '''
            }
        }
    }
}
