channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - dask
  - cartopy
  - cfgrib
  - click
  - matplotlib
  - netCDF4
  - pip
  - pytest
  - xarray
  - pip:
    # add pip requirements here if needed.
